services:
  node:
    build:
      context: .
      target: runner
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build:
      context: .
      target: nginx-runner
    ports:
      - "3000:80"
    depends_on:
      - node
    restart: unless-stopped

  app-dev:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: bun --bun run dev --host
    profiles:
      - dev
